### ISSUE TITLE
Replacement of images fails if image inside a table

### ISSUE THREAD

**Issue by cethegeek** [iulica/docx-mergefields#1]
Paragraphs inside tables are not returned by the doc.paragraphs. 

When a document has an image to be replaced in a table, while the code does find the image to be replaced just fine, it fails to find the paragraph with the image to implement the replacement because IncludePictureField.find_paragraph is traversing doc.paragraphs and ignoring every paragraph in tables.

I'll submit a PR with my possible fix.

Thanks.

**Comment by iulica** [comment]
Hi and thanks for the #2 . I just had a look and it seems ok. I'll test it tomorrow and merge it.

Best regards

**Comment by iulica** [comment]
Merged and released!
